In [ ]:
"""
Caracteristicas de algunos datos
0 : No
1 : Si


"""

In [55]:
#Importando librerias basicas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import scipy
import scipy.stats
warnings.simplefilter("ignore", UserWarning)

In [56]:
#Extrallendo dataset
data = pd.read_csv("../datasets/200610COVID19MEXICO.csv")


In [57]:
data.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [58]:
data.head(3)

FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  SECTOR  ENTIDAD_UM  SEXO  \
0          2020-06-10      0f69b4       2       3          15     2   
1          2020-06-10      1c79cc       2       3          15     2   
2          2020-06-10      140aab       2       4           9     2   

   ENTIDAD_NAC  ENTIDAD_RES  MUNICIPIO_RES  TIPO_PACIENTE  ... CARDIOVASCULAR  \
0            7           15            106              1  ...              2   
1           15           15            106              2  ...              2   
2            9            9              7              1  ...              2   

  OBESIDAD RENAL_CRONICA  TABAQUISMO  OTRO_CASO  RESULTADO  MIGRANTE  \
0        2             2           2          1          1        99   
1        2             2           2          2          1        99   
2        2             2           2         99          1        99   

   PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI  
0             México           99   97  
1             México           99    2  
2             México           99   97  

[3 rows x 35 columns]

# Select data 

In [59]:
cols = ['SEXO', 'INTUBADO', 'NEUMONIA', 'EDAD', 'EMBARAZO', 'DIABETES', 'EPOC', 'ASMA',
       'INMUSUPR', 'HIPERTENSION', 'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA',
       'TABAQUISMO', 'RESULTADO', 'FECHA_DEF']

In [60]:
#slect data where data have columns in cols

df = data[cols]

In [61]:
df.head()

SEXO  INTUBADO  NEUMONIA  EDAD  EMBARAZO  DIABETES  EPOC  ASMA  INMUSUPR  \
0     2        97         2    53        97         1     2     2         2   
1     2         2         1    59        97         2     2     2         2   
2     2        97         2    34        97         2     2     2         2   
3     2        97         2    45        97         2     2     2         2   
4     2         2         1    53        97         2     2     2         2   

   HIPERTENSION  CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  \
0             2               2         2              2           2   
1             2               2         2              2           2   
2             2               2         2              2           2   
3             2               2         2              2           2   
4             1               2         2              2           2   

   RESULTADO   FECHA_DEF  
0          1  9999-99-99  
1          1  9999-99-99  
2          1  9999-99-99  
3          1  9999-99-99  
4          1  9999-99-99

In [62]:
df.SEXO.unique()

array([2, 1])

In [63]:
df.EMBARAZO.unique()

array([97,  2,  1, 98])

In [64]:
df[['EMBARAZO', 'SEXO']][50:80]
# 2 - Hombre
# 1 - Mujer

# 1 - Si
# 2 - No

EMBARAZO  SEXO
50        97     2
51        97     2
52         2     1
53         2     1
54        97     2
55        97     2
56        97     2
57        97     2
58         2     1
59        97     2
60        97     2
61        97     2
62         2     1
63        97     2
64         2     1
65        97     2
66        97     2
67         2     1
68        97     2
69         1     1
70         2     1
71        97     2
72        97     2
73        97     2
74         2     1
75         2     1
76        97     2
77         2     1
78        97     2
79        97     2

In [65]:
df["EMBARAZO"] = np.where(df["EMBARAZO"] == 97, 0, df["EMBARAZO"])
df["EMBARAZO"] = np.where(df["EMBARAZO"] == 2, 0, df["EMBARAZO"])
df["EMBARAZO"] = np.where(df["EMBARAZO"] == 1, 1, df["EMBARAZO"])
df["EMBARAZO"] = np.where(df["EMBARAZO"] == 98, 0, df["EMBARAZO"])

<ipython-input-65-a30edd7210d8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["EMBARAZO"] = np.where(df["EMBARAZO"] == 97, 0, df["EMBARAZO"])
<ipython-input-65-a30edd7210d8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["EMBARAZO"] = np.where(df["EMBARAZO"] == 2, 0, df["EMBARAZO"])
<ipython-input-65-a30edd7210d8>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentat

In [66]:
def Chage_var(df, column, var_actual, var_new):
    return np.where(df[column] == var_actual, var_new, df[column])


In [67]:
df.head(3)

SEXO  INTUBADO  NEUMONIA  EDAD  EMBARAZO  DIABETES  EPOC  ASMA  INMUSUPR  \
0     2        97         2    53         0         1     2     2         2   
1     2         2         1    59         0         2     2     2         2   
2     2        97         2    34         0         2     2     2         2   

   HIPERTENSION  CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  \
0             2               2         2              2           2   
1             2               2         2              2           2   
2             2               2         2              2           2   

   RESULTADO   FECHA_DEF  
0          1  9999-99-99  
1          1  9999-99-99  
2          1  9999-99-99

In [68]:
df['NEUMONIA'] = Chage_var(df, 'NEUMONIA', 99, 0)

<ipython-input-68-dcd9404c5dce>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NEUMONIA'] = Chage_var(df, 'NEUMONIA', 99, 0)


In [71]:
df['NEUMONIA'] = Chage_var(df, 'NEUMONIA', 2, 0)

<ipython-input-71-369788e28dce>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NEUMONIA'] = Chage_var(df, 'NEUMONIA', 2, 0)


In [73]:
# 0 : No tiene
# 1 : Si tiene
df.NEUMONIA.value_counts()

0    309161
1     60201
Name: NEUMONIA, dtype: int64

In [82]:
#Intubados
df.INTUBADO.unique()

array([97,  2,  1, 99])

In [190]:
df['INTUBADO'] = Chage_var(df, 'INTUBADO', 2, 0)
df['INTUBADO'] = Chage_var(df, 'INTUBADO', 99, 0)
df['INTUBADO'] = Chage_var(df, 'INTUBADO', 97, 0)

<ipython-input-190-ed897491876c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['INTUBADO'] = Chage_var(df, 'INTUBADO', 2, 0)
<ipython-input-190-ed897491876c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['INTUBADO'] = Chage_var(df, 'INTUBADO', 99, 0)
<ipython-input-190-ed897491876c>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/

In [191]:
df.INTUBADO.unique()

array([0, 1])

In [205]:
#DIABETES
df['DIABETES'] = Chage_var(df, 'DIABETES', 1, 1)
df['DIABETES'] = Chage_var(df, 'DIABETES', 2, 0)
df['DIABETES'] = Chage_var(df, 'DIABETES', 98, 0)


<ipython-input-205-fcbf6bae2586>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DIABETES'] = Chage_var(df, 'DIABETES', 1, 1)
<ipython-input-205-fcbf6bae2586>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DIABETES'] = Chage_var(df, 'DIABETES', 2, 0)
<ipython-input-205-fcbf6bae2586>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/p

In [207]:
df.SEXO.unique()

array([2, 1])

In [208]:
#EPOC
df.EPOC.unique()

array([ 2,  1, 98])

In [209]:
df['EPOC'] = Chage_var(df, 'EPOC', 1, 1)
df['EPOC'] = Chage_var(df, 'EPOC', 2, 0)
df['EPOC'] = Chage_var(df, 'EPOC', 98, 0)
df.EPOC.unique()

<ipython-input-209-c23b7bfdc6d0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EPOC'] = Chage_var(df, 'EPOC', 1, 1)
<ipython-input-209-c23b7bfdc6d0>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EPOC'] = Chage_var(df, 'EPOC', 2, 0)
<ipython-input-209-c23b7bfdc6d0>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stabl

array([0, 1])

In [210]:
#ASMA
df.ASMA.unique()

array([ 2,  1, 98])

In [211]:
df['ASMA'] = Chage_var(df, 'ASMA', 1, 1)
df['ASMA'] = Chage_var(df, 'ASMA', 2, 0)
df['ASMA'] = Chage_var(df, 'ASMA', 98, 0)
df.EPOC.unique()

<ipython-input-211-ef10ad2335a4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ASMA'] = Chage_var(df, 'ASMA', 1, 1)
<ipython-input-211-ef10ad2335a4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ASMA'] = Chage_var(df, 'ASMA', 2, 0)
<ipython-input-211-ef10ad2335a4>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stabl

array([0, 1])

In [212]:
#INMUSUPR
df.INMUSUPR.unique()

array([ 2,  1, 98])

In [213]:
df['INMUSUPR'] = Chage_var(df, 'INMUSUPR', 1, 1)
df['INMUSUPR'] = Chage_var(df, 'INMUSUPR', 2, 0)
df['INMUSUPR'] = Chage_var(df, 'INMUSUPR', 98, 0)
df.EPOC.unique()

<ipython-input-213-b897a4d13b72>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['INMUSUPR'] = Chage_var(df, 'INMUSUPR', 1, 1)
<ipython-input-213-b897a4d13b72>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['INMUSUPR'] = Chage_var(df, 'INMUSUPR', 2, 0)
<ipython-input-213-b897a4d13b72>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/p

array([0, 1])

In [214]:
df.head()

SEXO  INTUBADO  NEUMONIA  EDAD  EMBARAZO  DIABETES  EPOC  ASMA  INMUSUPR  \
0     2         0         0    53         0         1     0     0         0   
1     2         0         1    59         0         0     0     0         0   
2     2         0         0    34         0         0     0     0         0   
3     2         0         0    45         0         0     0     0         0   
4     2         0         1    53         0         0     0     0         0   

   HIPERTENSION  CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  \
0             2               2         2              2           2   
1             2               2         2              2           2   
2             2               2         2              2           2   
3             2               2         2              2           2   
4             1               2         2              2           2   

   RESULTADO   FECHA_DEF  
0          1  9999-99-99  
1          1  9999-99-99  
2          1  9999-99-99  
3          1  9999-99-99  
4          1  9999-99-99

In [215]:
#HIPERTENSION
df.HIPERTENSION.unique()

array([ 2,  1, 98])

In [216]:
df['HIPERTENSION'] = Chage_var(df, 'HIPERTENSION', 1, 1)
df['HIPERTENSION'] = Chage_var(df, 'HIPERTENSION', 2, 0)
df['HIPERTENSION'] = Chage_var(df, 'HIPERTENSION', 98, 0)
df.EPOC.unique()

<ipython-input-216-1f092e92faef>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HIPERTENSION'] = Chage_var(df, 'HIPERTENSION', 1, 1)
<ipython-input-216-1f092e92faef>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HIPERTENSION'] = Chage_var(df, 'HIPERTENSION', 2, 0)
<ipython-input-216-1f092e92faef>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pan

array([0, 1])

In [220]:
#CARDIOVASCULAR
df.CARDIOVASCULAR.unique()

array([0, 1])

In [218]:
df['CARDIOVASCULAR'] = Chage_var(df, 'CARDIOVASCULAR', 1, 1)
df['CARDIOVASCULAR'] = Chage_var(df, 'CARDIOVASCULAR', 2, 0)
df['CARDIOVASCULAR'] = Chage_var(df, 'CARDIOVASCULAR', 98, 0)
df.CARDIOVASCULAR.unique()

<ipython-input-218-338a9504fcce>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CARDIOVASCULAR'] = Chage_var(df, 'CARDIOVASCULAR', 1, 1)
<ipython-input-218-338a9504fcce>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CARDIOVASCULAR'] = Chage_var(df, 'CARDIOVASCULAR', 2, 0)
<ipython-input-218-338a9504fcce>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: htt

array([0, 1])

In [219]:
#OBESIDAD
df.OBESIDAD.unique()

array([ 2,  1, 98])

In [221]:
df['OBESIDAD'] = Chage_var(df, 'OBESIDAD', 1, 1)
df['OBESIDAD'] = Chage_var(df, 'OBESIDAD', 2, 0)
df['OBESIDAD'] = Chage_var(df, 'OBESIDAD', 98, 0)
df.OBESIDAD.unique()

<ipython-input-221-4145ad25b13b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['OBESIDAD'] = Chage_var(df, 'OBESIDAD', 1, 1)
<ipython-input-221-4145ad25b13b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['OBESIDAD'] = Chage_var(df, 'OBESIDAD', 2, 0)
<ipython-input-221-4145ad25b13b>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/p

array([0, 1])

In [222]:
df.head(3)

SEXO  INTUBADO  NEUMONIA  EDAD  EMBARAZO  DIABETES  EPOC  ASMA  INMUSUPR  \
0     2         0         0    53         0         1     0     0         0   
1     2         0         1    59         0         0     0     0         0   
2     2         0         0    34         0         0     0     0         0   

   HIPERTENSION  CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  \
0             0               0         0              2           2   
1             0               0         0              2           2   
2             0               0         0              2           2   

   RESULTADO   FECHA_DEF  
0          1  9999-99-99  
1          1  9999-99-99  
2          1  9999-99-99

In [223]:
#RENAL_CRONICA
df.RENAL_CRONICA.unique()

array([ 2,  1, 98])

In [224]:
df['RENAL_CRONICA'] = Chage_var(df, 'RENAL_CRONICA', 1, 1)
df['RENAL_CRONICA'] = Chage_var(df, 'RENAL_CRONICA', 2, 0)
df['RENAL_CRONICA'] = Chage_var(df, 'RENAL_CRONICA', 98, 0)
df.RENAL_CRONICA.unique()

<ipython-input-224-4ec644ea61bd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RENAL_CRONICA'] = Chage_var(df, 'RENAL_CRONICA', 1, 1)
<ipython-input-224-4ec644ea61bd>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RENAL_CRONICA'] = Chage_var(df, 'RENAL_CRONICA', 2, 0)
<ipython-input-224-4ec644ea61bd>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https:/

array([0, 1])

In [225]:
#TABAQUISMO
df.TABAQUISMO.unique()

array([ 2,  1, 98])

In [226]:
df['TABAQUISMO'] = Chage_var(df, 'TABAQUISMO', 1, 1)
df['TABAQUISMO'] = Chage_var(df, 'TABAQUISMO', 2, 0)
df['TABAQUISMO'] = Chage_var(df, 'TABAQUISMO', 98, 0)
df.RENAL_CRONICA.unique()

<ipython-input-226-e407c7a9f498>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TABAQUISMO'] = Chage_var(df, 'TABAQUISMO', 1, 1)
<ipython-input-226-e407c7a9f498>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TABAQUISMO'] = Chage_var(df, 'TABAQUISMO', 2, 0)
<ipython-input-226-e407c7a9f498>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pyda

array([0, 1])

In [227]:
#RESULTADO
df.RESULTADO.unique()

array([1, 2, 3])

In [229]:
df['RESULTADO'] = Chage_var(df, 'RESULTADO', 1, 1)
df['RESULTADO'] = Chage_var(df, 'RESULTADO', 2, 0)
df['RESULTADO'] = Chage_var(df, 'RESULTADO', 98, 0)
df.RESULTADO.unique()

<ipython-input-229-daacb2c663b9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RESULTADO'] = Chage_var(df, 'RESULTADO', 1, 1)
<ipython-input-229-daacb2c663b9>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RESULTADO'] = Chage_var(df, 'RESULTADO', 2, 0)
<ipython-input-229-daacb2c663b9>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.o

array([1, 0, 3])

In [230]:
df['RESULTADO'] = Chage_var(df, 'RESULTADO', 3, 0)

<ipython-input-230-ff426fedbcdd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RESULTADO'] = Chage_var(df, 'RESULTADO', 3, 0)


In [231]:
df.RESULTADO.unique()

array([1, 0])

In [233]:
df.FECHA_DEF.value_counts()

9999-99-99    347796
2020-05-25       537
2020-06-01       503
2020-05-18       498
2020-05-27       487
               ...  
2020-03-11         1
2020-02-20         1
2020-03-20         1
2020-02-23         1
2020-02-05         1
Name: FECHA_DEF, Length: 103, dtype: int64

In [234]:
m = df.FECHA_DEF
m

0         9999-99-99
1         9999-99-99
2         9999-99-99
3         9999-99-99
4         9999-99-99
             ...    
369357    9999-99-99
369358    9999-99-99
369359    9999-99-99
369360    9999-99-99
369361    9999-99-99
Name: FECHA_DEF, Length: 369362, dtype: object

In [236]:
l = []
for j in m:
    if j != '9999-99-99':
        x = 0
        l.append(x)
    else:
        x = 1
        l.append(x)

In [238]:
df['DEF'] = l

<ipython-input-238-28f17cf3f030>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DEF'] = l


In [240]:
df.head(40)

SEXO  INTUBADO  NEUMONIA  EDAD  EMBARAZO  DIABETES  EPOC  ASMA  INMUSUPR  \
0      2         0         0    53         0         1     0     0         0   
1      2         0         1    59         0         0     0     0         0   
2      2         0         0    34         0         0     0     0         0   
3      2         0         0    45         0         0     0     0         0   
4      2         0         1    53         0         0     0     0         0   
5      1         0         0    64         0         0     0     0         0   
6      1         0         0    29         0         0     0     0         0   
7      1         0         0    41         0         1     0     0         0   
8      2         0         0    53         0         0     0     0         0   
9      2         0         0    26         0         0     0     0         0   
10     2         0         0    52         0         0     0     0         0   
11     1         0         1    62         0         1     0     0         0   
12     2         0         0    43         0         0     0     0         0   
13     2         0         0    34         0         0     0     0         0   
14     2         0         0    56         0         1     0     0         0   
15     2         0         0    61         0         1     0     0         0   
16     2         0         1    72         0         1     0     0         0   
17     2         0         0    56         0         0     0     0         0   
18     1         0         0    48         0         1     0     0         0   
19     2         0         0    45         0         0     0     0         0   
20     2         0         0    63         0         0     0     0         0   
21     1         0         1    37         0         0     0     0         0   
22     2         0         1    74         0         1     0     0         0   
23     2         0         0    28         0         0     0     0         0   
24     1         0         0    27         0         0     0     0         0   
25     2         0         0    71         0         0     0     0         0   
26     2         0         0    55         0         0     0     0         0   
27     1         0         0    40         0         0     0     0         0   
28     1         0         0    34         0         0     0     0         0   
29     1         0         0    31         0         0     0     0         0   
30     2         0         1    37         0         0     0     0         0   
31     1         0         0    25         0         0     0     0         0   
32     1         0         0    32         0         0     0     0         0   
33     1         0         0    57         0         0     0     1         0   
34     2         0         0    57         0         0     0     0         0   
35     1         0         0    45         0         0     0     0         0   
36     2         0         0    40         0         0     0     0         0   
37     1         0         0    52         0         0     0     0         0   
38     1         0         1    48         0         1     0     0         0   
39     1         0         1    45         0         0     0     0         0   

    HIPERTENSION  CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  \
0              0               0         0              0           0   
1              0               0         0              0           0   
2              0               0         0              0           0   
3              0               0         0              0           0   
4              1               0         0              0           0   
5              0               0         0              0           0   
6              0               0         1              0           0   
7              0               0         0              0           1   
8              0               0         0              0         

In [241]:
del df['FECHA_DEF']

In [242]:
df.head(4)

SEXO  INTUBADO  NEUMONIA  EDAD  EMBARAZO  DIABETES  EPOC  ASMA  INMUSUPR  \
0     2         0         0    53         0         1     0     0         0   
1     2         0         1    59         0         0     0     0         0   
2     2         0         0    34         0         0     0     0         0   
3     2         0         0    45         0         0     0     0         0   

   HIPERTENSION  CARDIOVASCULAR  OBESIDAD  RENAL_CRONICA  TABAQUISMO  \
0             0               0         0              0           0   
1             0               0         0              0           0   
2             0               0         0              0           0   
3             0               0         0              0           0   

   RESULTADO  DEF  
0          1    1  
1          1    1  
2          1    1  
3          1    1

In [244]:
#Datos listos
df.to_csv('../datasets/data_predict.csv')

In [74]:
#0 = No
#1 = si